import Head from 'next/head'
import {useEffect, useState} from "react";
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
   const [location, setLocation] = useState(null);
   const [v_data, setData] = useState(null);

   useEffect(() => {
        const fetchData = async () => {
            const response = await fetch('http://api.weatherapi.com/v1/current.json?key=203f79b78a4f427ebd8212359232508&q=Limassol&aqi=no');
            const data = await response.json();
            setLocation(data);
            console.log(data)
            setData(data)

        }
       fetchData();
        }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       <div>
           <h1>{v_data.current.temp_c}</h1>
           <h1>{v_data.location.country}</h1>
       </div>
      </main>
    </>
  )
}
